### ISSUE TITLE
Wrong coefficients of linear expressions after setting constraints

### ISSUE THREAD

**Issue by fteicht** [coin-or/Rehearse#1] opened 2016-03-29 16:09 UTC
Hi,

Congratulations and many thanks for the work on the rehearse library. It is a must-have to easily model (I)LP problems since the flopc++ library seems to be inactive for many years.

I noticed that rehearse seems to unexpectedly modify the coefficients of linear expressions for some obscure reasons.
For instance, I set an expression which is the sum of boolean expressions and want this sum to be less than 1 as below:

// CODE BEGIN
CelExpression expr;
for (const auto& element : myset) {
    auto i = m_variables.find(std::make_pair(element));
    if (i != m_variables.end()) {
        expr += i->second;
    }
}
m_model->addConstraint(expr <= 1);
// CODE END

Sometimes it works, but some other times all the coefficients of value 1 become 3. When what seems to be a bug occurs, then all impacted constraints have coefficients of value 3 instead of 1.
I have not even the constant 3 in my code so I don't know where these coefficients come from.

Thanks,
Florent.

**Comment by Celebio** [comment] 2016-03-30 09:39
Hi Florent,
Thanks for your report.

Is it possible to provide an entire compilable example so I can investigate?

Thanks,
Onur

**Comment by fteicht** [comment] 2016-04-01 16:48
Hi Onur,

My code is included in a large project where the ILP problem is generated from data.
By trying to model a simple version of the problem with naive data I could not get the same symptoms. However I still get wrong solutions.

Before posting the code, let me say that I noticed that the bug comes from the way I use variable containers. The rehearse library provides a CelBoolVarArray class to help manage arrays of variables. However, my variables cannot be easily stored in arrays because I don't have the same numbers of second-dimension variables for each index of the first dimension. Therefore I stored my variables in a map. But for the purpose of the code below I could also get wrong results by storing variables into an array of type std::vector<std::vector<CelBoolVar> > which should be equivalent to CelBoolVarArray in principle. Since I don't get the same solution to the problem there are not equivalent at all. Why must we store sets of variables into Cel[Bool|Int|Num]VarArray?

Moreover, I discovered another bug, this time using the recommend CelBoolVarArray. If the dimensions of the array are too large I get a segfault when the model is transferred to the solver.

Below is the code to reproduce the 2 bugs (comment or uncomment lines appropriately):

```
// Compile with the following line
// g++ -o test_rehearse `pkg-config --cflags rehearse` test_rehearse.cc `pkg-config --libs rehearse osi-cbc`

#include <coin/OsiSolverInterface.hpp>
#include <coin/OsiCbcSolverInterface.hpp>
#include <coin/CelModel.h>
#include <coin/CelBoolVarArray.h>
#include <vector>

// It's the task assignment problems: assign objects in A to objects in B so as to maximize the overall revenue
// Decision variables: x(a,b) in {0,1} for each a in A and b in B
// R(a,b)=exp(cos(2*PI*a*b/A*B)) is the revenue of the assignment pair (a,b)
// max sum_{a in A, b in B} x(a,b) * R(a,b)
// for each a in A: sum(b in B) x(a,b) <= 1
// for each b in B: sum(a in A) x(a,b) <= 1

int main() {
	// Multiplying the following A and B by 10 results in a segfault when building the model
	unsigned int A = 20;
	unsigned int B = 10;
	double PI = std::acos(-1.0);
	
	std::cout << "Modeling..." << std::endl;
	OsiCbcSolverInterface solver;
	CelModel model(solver);
	CelBoolVarArray x;
	x.multiDimensionResize(2, A, B);
// Commenting the 2 previous lines and commenting out the following one results in a buggy model
//	std::vector<std::vector<CelBoolVar> > x(A, std::vector<CelBoolVar>(B));
	CelExpression objective;
	
	// Objective (why can't it be called interleaved with addConstraint but before all the addConstraint?)
	
	for (unsigned int a = 0 ; a < A ; a++) {
		for (unsigned int b = 0 ; b < B ; b++) {
			objective += std::exp(std::cos(2.0*PI*a*b/(A*B))) * x[a][b];
		}
	}
	
	model.setObjective(objective);
	
	// Constraints
	
	for (unsigned int a = 0 ; a < A ; a++) {
		CelExpression cst;
		for (unsigned int b = 0 ; b < B ; b++) {
			objective += std::exp(std::cos(2.0*PI*a*b/(A*B))) * x[a][b];
			cst += x[a][b];
		}
		model.addConstraint(cst <= 1);
	}
	
	for (unsigned int b = 0 ; b < B ; b++) {
		CelExpression cst;
		for (unsigned int a = 0 ; a < A ; a++) {
			cst += x[a][b];
		}
		model.addConstraint(cst <= 1);
	}
	
	solver.setObjSense(-1.0);
	model.builderToSolver();
//	solver.writeLp("assignment");
	std::cout << "Optimizing..." << std::endl;
	solver.initialSolve();
	solver.branchAndBound();
	std::cout << "Assignments:" << std::endl;
	
	for (unsigned int a = 0 ; a < A ; a++) {
		for (unsigned int b = 0 ; b < B ; b++) {
			if (model.getSolutionValue(x[a][b]) == 1) {
				std::cout << "   " << a << " -> " << b << std::endl;
			}
		}
	}
	
	return 0;
}
```

Thanks for your help!
Florent

**Comment by Celebio** [comment] 2016-04-04 17:31
Hi Florent,

Could you please check out the last commit?
The latest version works with larger lp problems and (almost) supports std::vector as container. 

I say "almost" because by design of Rehearse stl containers are not meant to be used : the expression tree keeps a pointer to variables which are also (polymorphic) CelExpression`s so we must guarantee they are not destroyed too early.

Thus the existence of Cel[Bool|Int|Num]VarArray, but your usecase seems to be justified. I fixed the bug with CelBoolVariable used in a stl container so it works but I think you will have some trouble if the container resizes. But even in this case we can manage to avoid destruction of CelVariable`s with a custom wrapper that behaves like unique_ptr (I am not sure but unique_ptr may be sufficient by itself).

I may also consider to add CelExpression-compliant map-like structure to handle this usecase.

Regards,
Onur

**Comment by Celebio** [comment] 2017-12-12 22:08
No answer. Closing issue

**Closed by Celebio** 2017-12-12 22:08 UTC
